### ISSUE TITLE
Pinot Client won't handle broker failure scenario

### ISSUE THREAD

**Issue by fx19880617** [linkedin/pinot#120]
We init com.linkedin.pinot.client.Connection with the brokerlist fetched from ConnectionFactory.
But if one of the broker failed after connection initialized, then we will have issues.
Any plan to fix this?
Some possible solutions:
1. putting data change listener on /EXTERNALVIEW/brokerResource and update broker list when change happens;
2. retry on other nodes + active fetch online broker list when fails

**Comment by kishoreg** [comment]
I thought there was another option to initialize it with Zookeeper and we
would listen to EXTERNAVIEW. Looks like that not the case.

**Comment by fx19880617** [comment]
That's the option 1, basically we have a zkclient per pinot client.

**Comment by fx19880617** [comment]
close as supported now
