### ISSUE TITLE
TimeFieldSpec["defaultNullValue"] error

### ISSUE THREAD

**Issue by caozhenhuamail** [linkedin/pinot#124]
About Error: org.codehaus.jackson.map.JsonMappingException: N/A (through reference chain: com.linkedin.pinot.common.data.Schema["timeFieldSpec"]->com.linkedin.pinot.common.data.TimeFieldSpec["defaultNullValue"])

**Comment by kishoreg** [comment]
Is this happening in new code. Can you add give me your schema json file.

**Comment by laloyd** [comment]
Aloha, I'm having the same issue.  Here is my schema file:

pinot-0.016-pkg laloyd$ cat sample_data/flights/flights-schema.json
{
  "dimensionFieldSpecs" : [
    {
      "name": "Year",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Month",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Carrier",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Origin",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "Dest",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name": "DivAirports",
      "dataType" : "STRING",
      "delimiter" : null,
      "singleValueField" : false
    }
  ],
  "timeFieldSpec" : {
    "incomingGranularitySpec" : {
      "timeType" : "DAYS",
      "dataType" : "INT",
      "name" : "DaysSinceEpoch"
    }
  },
  "metricFieldSpecs" : [
    {
      "name" : "Delayed",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name" : "Cancelled",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    },
    {
      "name" : "Diverted",
      "dataType" : "INT",
      "delimiter" : null,
      "singleValueField" : true
    }
   ],
  "schemaName" : "flights"
}

**Comment by Jackie-Jiang** [comment]
Duplicate issue with #123 , I will close this one and keep all discussion in #123
