### ISSUE TITLE
How to deploy a Pinot Cluster?

### ISSUE THREAD

**Issue by ChenJianJunCJJ** [linkedin/pinot#125]
When I deploy Pinot cluster on three machines and create the table of "flights" success, but the table cannot connect to schema.
The process as follows:
1, bin/pinot-admin.sh StartController -controllerHost server0 -dataDir /tmp/PinotController -zkAddress server0:2181,server1:2181,server2:2181 -clusterName PinotCluster &
2, bin/pinot-admin.sh StartBroker -brokerHost server0 -brokerPort 8099 -zkAddress server0:2181,server1:2181,server2:2181 -clusterName PinotCluster &
3, bin/pinot-admin.sh StartServer -serverHost server0 -serverPort 8098 -dataDir /tmp/PinotServer -segmentDir /tmp/PinotServer/segment -zkAddress server0:2181,server1:2181,server2:2181 -clusterName PinotCluster &
4, bin/pinot-admin.sh AddSchema -controllerHost server0 -controllerPort 9000 -schemaFile /home/cos/bigData/flights/flights-schema.json -exec
5, bin/pinot-admin.sh AddTable -filePath /home/cos/bigData/flights/flights-definition-realtime.json -controllerHost server0 -controllerPort 9000 -exec
6, bin/pinot-admin.sh ShowClusterInfo -zkAddress server0:2181,server1:2181,server2:2181 -clusterName PinotCluster

Result of step6:
Connecting to Zookeeper at: server0:2181,server1:2181,server2:2181
!!com.linkedin.pinot.tools.admin.command.ShowClusterInfoCommand$ClusterInfo
brokerInfoList:
- name: Broker_192.168.170.153_8099
  state: ONLINE
  tags: [DefaultTenant_BROKER]
clusterName: PinotCluster
controllerInfo: {leaderName: server0_9000}
serverInfoList:
- name: Server_server0_8098
  state: ONLINE
  tags: [DefaultTenant_OFFLINE, DefaultTenant_REALTIME]
tableInfoList:
- segmentInfoList:
  - name: flights_REALTIME_1464247100427_0__0__1464247101424
    segmentStateMap: {Server_server0_8098: ONLINE}
  tableName: flights_REALTIME
  tag: flights_REALTIME

The result of query (select * from flights limit 10):
{
    "traceInfo": {},
    "numDocsScanned": 0,
    "timeUsedMs": 69,
    "segmentStatistics": [],
    "exceptions": [],
    "totalDocs": 0
}

**Comment by raviarin** [comment]
Can you try to look at logs or see what is printed on console for broker server? Do they get the queries you send? How do you send the query?

**Comment by ChenJianJunCJJ** [comment]
There are no error or exception in "pinotBroker.log". I use the web console (http://controllerHost:9000/query/#)  to interact with Pinot.

**Comment by kishoreg** [comment]
looks like you have created a realtime table for flights. Have you
configured the kafka topic for flights data. Do you see any errors in
server log?

**Comment by ChenJianJunCJJ** [comment]
I have saved this problem. It is a long story, if you want the detail then massage me.
