### ISSUE TITLE
Data was changed itself

### ISSUE THREAD

**Issue by 1teed** [linkedin/pinot#14]
Hello

I'm so interested in Pinot that I try to test it.
I'm in trouble with below issue.

I sended data to the realtime node using kafka.
After a while, data was changed itself.

First result are as follows: (sql query result)

<pre>
{
    "exceptions": [],
    "traceInfo": {},
    "timeUsedMs": 1,
    "totalDocs": 56700,
    "segmentStatistics": [],
    "aggregationResults": [],
    "selectionResults": {
        "results": [
            ["A", "1435048500111", "1"],
            ["A", "1435048500113", "1"],
            ["A", "1435048500115", "1"],
            ["A", "1435048500117", "1"],
            ["A", "1435048500119", "1"],
        ],
        "columns": ["name", "time", "value"]
    },
    "numDocsScanned": 5
}
</pre>

But after a while, the value of column "value" was changed itself.
Next same query result are as follows: (sql query result)

<pre>
{
    "exceptions": [],
    "traceInfo": {},
    "timeUsedMs": 1,
    "totalDocs": 56700,
    "segmentStatistics": [],
    "aggregationResults": [],
    "selectionResults": {
        "results": [
            ["A", "1435048500111", "0"],
            ["A", "1435048500113", "0"],
            ["A", "1435048500115", "0"],
            ["A", "1435048500117", "0"],
            ["A", "1435048500119", "0"],
        ],
        "columns": ["name", "time", "value"]
    },
    "numDocsScanned": 5
}
</pre>

Is that because the column name, "value" is reserved keyword?

cf.
_schema file_

<pre>
{
        "dimensionFieldSpecs" : [
                {
                        "name": "name",
                        "dataType" : "STRING",
                        "delimiter" : null,
                        "singleValueField" : true
                }
        ],
        "timeFieldSpec" : {
                "incomingGranularitySpec" : {
                        "timeType" : "MILLISECONDS",
                        "dataType" : "LONG",
                        "name" : "time"
                }
        },
        "metricFieldSpecs" : [
                {
                        "name" : "value",
                        "dataType" : "INT",
                        "delimiter" : null,
                        "singleValueField" : true
                }
        ],
        "schemaName" : "loadTest"
}
</pre>

_table file_

<pre>
{
    "tableName":"loadTest",
    "segmentsConfig" : {
        "retentionTimeUnit":"DAYS",
        "retentionTimeValue":"7",
        "segmentPushFrequency":"daily",
        "segmentPushType":"APPEND",
        "replication" : "1",
        "schemaName" : "loadTest",
        "timeColumnName" : "time",
        "timeType" : "MILLISECONDS",
        "segmentAssignmentStrategy" : "BalanceNumSegmentAssignmentStrategy"
    },
    "tableIndexConfig" : {
        "invertedIndexColumns" : ["time"],
        "loadMode"  : "HEAP",
        "lazyLoad"  : "false",
                "streamConfigs": {
                        "streamType": "kafka",
                        "stream.kafka.consumer.type": "highLevel",
                        "stream.kafka.topic.name": "loadTest",
                        "stream.kafka.decoder.class.name": "com.linkedin.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder",
                        "stream.kafka.zk.broker.url": "localhost:2181",
                        "stream.kafka.hlc.zk.connect.string": "localhost:2181"
                }
    },
    "tableType":"REALTIME",
        "tenants" : {
                "broker":"brokerOne",
                "server":"serverOne"
        },
    "metadata": {
    }
}
</pre>

So is this an issue?
Thanks.

**Comment by dhaval2025** [comment]
hey can you paste the query you are running here. 

Thanks

**Comment by Jackie-Jiang** [comment]
Closed due to no reply and cannot reproduce.
