### ISSUE TITLE
How I set configuration about store data for only 10 minutes in real-time node?

### ISSUE THREAD

**Issue by 1teed** [linkedin/pinot#15]
I have some question about retentionTime.

I want to store the data in Real-time node with only 10 minutes.
And I tested below configuration :

<pre>
{
    "tableName":"loadTest",
    "segmentsConfig" : {
        "retentionTimeUnit":"MINUTES",
        "retentionTimeValue":"10",
        "segmentPushFrequency":"daily",
        "segmentPushType":"APPEND",
        "replication" : "1",
        "schemaName" : "loadTest",
        "timeColumnName" : "time",
        "timeType" : "MILLISECONDS",
        "segmentAssignmentStrategy" : "BalanceNumSegmentAssignmentStrategy"
    },
    "tableIndexConfig" : {
        "loadMode"  : "HEAP",
        "lazyLoad"  : "false",
                "streamConfigs": {
                        "streamType": "kafka",
                        "stream.kafka.consumer.type": "highLevel",
                        "stream.kafka.topic.name": "loadTest",
                        "stream.kafka.decoder.class.name": "com.linkedin.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder",
                        "stream.kafka.zk.broker.url": "localhost:2181",
                        "stream.kafka.hlc.zk.connect.string": "localhost:2181"
                }
    },
    "tableType":"REALTIME",
        "tenants" : {
                "broker":"brokerOne",
                "server":"serverOne"
        },
    "metadata": {
    }
}
</pre>

An error had occurred.

<pre>
2015/06/24 17:18:53.593 ERROR [com.linkedin.pinot.controller.helix.core.retention.RetentionManager] [] Error creating TimeRetentionStrategy for table: loadTest_REALTIME, Exception: java.lang.NullPointerException
</pre>

Can you explain about retention configurations?
How I set configuration about store data for only 10 minutes in real-time node?

**Comment by dhaval2025** [comment]
Hey @1teed the issue is that the realtime flush time and size by default is 1hour and 5M documents respectively, you should add the following 2 properties to the stream configs ... 

"realtime.segment.flush.threshold.time" : "3600000",
 "realtime.segment.flush.threshold.size" : "50000"

and set the flush time to something smaller than 10 minutes, and try it out again. 

Also remember to pull the latest.
