### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by tkao1000** [linkedin/pinot#152]
Hi,

Could someone point me to the code where the broker decides which segments are relevant based on a query with time boundaries?

Thanks a lot

**Comment by jfim** [comment]
In the current code, it just sends out the query to all segments. The segments are pruned quickly at the beginning of the query phase in the case of a query with time boundaries, as the time column cannot contain data that matches the predicate.

The routing table is built at https://github.com/linkedin/pinot/blob/32a5f91cf02e33314d6c1e2c2d823eecc0accc6f/pinot-transport/src/main/java/com/linkedin/pinot/routing/builder/BalancedRandomRoutingTableBuilder.java#L40-L40

**Comment by kishoreg** [comment]
@tkao1000  can we close this?

**Comment by tkao1000** [comment]
Oh yeah, sorry about that
