### ISSUE TITLE
Adding schema/table in realtime mode

### ISSUE THREAD

**Issue by erlis1** [linkedin/pinot#20]
Hello.

Have you changed something in terms of adding schema/table in realtime (kafka) mode?
I'm using the same files for schema/table that i've been using since my first test last week, and always after a command './pinot-admin AddSchema ...' there was a feedback line printed to stdout with some info, as well as after the '/pinot-admin AddTable ...' command.

I add schema and table after running broker, controller and server.

Since last Jun26 there no such printouts anymore, and the query returns 'no table hit' error, and there's no consumption from kafka, as expected...

Thanks.

**Comment by mayankshriv** [comment]
Please try the -exec switch with these commands (refer to pinot-admin wiki), and let us know if you still see an issue. As for messages not being printed, we will resolve those shortly.

**Comment by dongyanfeng** [comment]
Class AddTableCommand:
 code:
 if (!_exec) {
      LOGGER.warn("Dry Running Command: " + toString());
      LOGGER.warn("Use the -exec option to actually execute the command.");
      return true;
    }
##_exec == false(default)  return true
