### ISSUE TITLE
File upload doesn't work with latest pinot controller

### ISSUE THREAD

**Issue by jamesyfshao** [linkedin/pinot#2007]
FileUploadUtils.sendSegmentUriImpl(...) has issue sending segment file URI to pinot controller. In the recent Pinot controller changes, we enforced the checking of "Content-Type" of the requests and reject (by returning 400) the caller if it doesn't contain a valid information. This is usually fine in other Java request code section as Apache Http libs can infer and generate the content type from the entity provided to it. However, when the entity is empty (like the case we have here), it will not generate a proper content-type and Pinot Controller will reject such request. [This fix](https://github.com/linkedin/pinot/pull/2006) and the unit-test should ensure that file upload request should do the correct thing.

Pull request: https://github.com/linkedin/pinot/pull/2006

**Comment by jenniferdai** [comment]
Merged your change, thanks for catching this!
