### ISSUE TITLE
After the restart, why want to delete the data

### ISSUE THREAD

**Issue by dongyanfeng** [linkedin/pinot#21]
class  StartControllerCommand.java 
line 123:
    if (zkClient.exists(helixClusterName)) {
      zkClient.deleteRecursive(helixClusterName);
    }

**Comment by mayankshriv** [comment]
This is not required, and will be removed from the code shortly.

**Comment by mayankshriv** [comment]
The code has been removed. Additionally, a new command 'DeleteCluster' has been to assist with deleting a cluster.
