### ISSUE TITLE
Kafka 0.9+ support

### ISSUE THREAD

**Issue by alex-hofsteede** [linkedin/pinot#2418]
From the look of the `streamConfigs` [here](https://github.com/linkedin/pinot/wiki/How-To-Use-Pinot) it appears that Pinot supports only the kafka 0.7-0.8 consumers requiring a zookeeper connection string. 

Kafka 0.9+ has updated this with `bootstrap.servers` configuration. Is there a plan to support this in pinot?

**Comment by kishoreg** [comment]
That wiki probably needs to be updated. @jenniferdai @mcvsubbu @jfim will have more info

**Comment by alex-hofsteede** [comment]
An example of a working realtime pinot table config using a remote kafka 0.9+ broker would be super helpful.

**Comment by jenniferdai** [comment]
The following for airlineStats_realtime_table_config.json in pinot-tools/src/main/resources/sample_data/ should allow you to post a table and create a consuming segment:

{
  "tableName": "airlineStats",
  "tableType": "REALTIME",
  "segmentsConfig": {
    "timeColumnName": "DaysSinceEpoch",
    "timeType": "DAYS",
    "retentionTimeUnit": "DAYS",
    "retentionTimeValue": "5",
    "segmentPushType": "APPEND",
    "segmentAssignmentStrategy": "BalanceNumSegmentAssignmentStrategy",
    "schemaName": "airlineStats",
    "replication": "1",
    "replicasPerPartition": "1"
  },
  "tenants": {
    "broker": "airline_broker",
    "server": "airline"
  },
  "tableIndexConfig": {
    "loadMode": "MMAP",
    "streamConfigs": {
      "streamType": "kafka",
      "stream.kafka.consumer.type": "simple",
      "stream.kafka.topic.name": "flights-realtime",
      "stream.kafka.decoder.class.name": "com.linkedin.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder",
      "stream.kafka.hlc.zk.connect.string": "localhost:2191/kafka",
      "stream.kafka.zk.broker.url": "localhost:2191/kafka",
      "stream.kafka.broker.list": "localhost:19092",
      "realtime.segment.flush.threshold.time": "3600000",
      "realtime.segment.flush.threshold.size": "50000",
      "stream.kafka.consumer.prop.auto.offset.reset": "smallest"
    }
  },
  "metadata": {
    "customConfigs": {}
  }
}

**Comment by jenniferdai** [comment]
@alex-hofsteede Did that work for you?

**Comment by alex-hofsteede** [comment]
@jenniferdai IIUC this config still implies a zookeeper dependency (`stream.kafka.zk.broker.url` etc), I was looking for a solution along the lines of the [new consumer](https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/) which replaces the old simple and highlevel consumers and removes the client dependency on Zookeeper to store topic offsets. Is that something that Pinot supports?

**Comment by kishoreg** [comment]
Pinot uses low-level Kafka consumer and manages its own offsets.  This mean
Pinot does not rely on Kafka (either broker or Kafka zookeeper) for storing
the offsets.

Does that answer your question?

**Comment by alex-hofsteede** [comment]
@kishoreg I think so, just to clarify, does that mean that `stream.kafka.hlc.zk.connect.string` and`stream.kafka.zk.broker.url` can always just be a local zookeeper instance for pinot offset management, unrelated to the remote kafka broker that I am consuming from?

**Comment by kishoreg** [comment]
we might still need that to find the leader broker for a kafka partition
and also detect the change in number of partitions but we dont need it to
store offsets.

Subbu/Jf, please confirm.

thanks,
Kishore G

**Comment by jfim** [comment]
There are two Kafka consumer implementations in Pinot: an older deprecated consumer that uses the older Kafka high level consumer (from the 0.7-0.8 APIs, which uses ZK for offset management), and a newer consumer that connects directly to the Kafka brokers and handles offset management within Pinot.

We have updated the documentation to use the newer consumer (the part that says `"stream.kafka.consumer.type": "simple"`). The older properties `stream.kafka.hlc.zk.connect.string` and `stream.kafka.zk.broker.url` that refer to Kafka 0.7/0.8 ZK-based offset management are effectively ignored with the new consumer; we just have the older consumer still present for backwards compatibility reasons.

I can't remember offhand if these properties are still required (they shouldn't) or if you can create a table without specifying them. If it gives an error if those properties are absent and you're using the newer consumer, ping me, that shouldn't happen.

**Comment by mcvsubbu** [comment]
@alex-hofsteede you do not need the zk connection configuration for the newer Low-level consumer configuration.

**Comment by alex-hofsteede** [comment]
Great, I was able to get ingestion working with a config based on the one in https://github.com/linkedin/pinot/pull/2421 (without the `.zk.` config options) Thanks so much @jenniferdai @kishoreg @jfim !
