### ISSUE TITLE
Add support for escaped identifiers

### ISSUE THREAD

**Issue by subprotocol** [linkedin/pinot#2687]
I have a use case were our columns are named with periods in them.   For example : "user.email"

Looking at PQL2.g4 it looks like Pinot only supports identifiers as such:
```IDENTIFIER: [A-Za-z_][A-Za-z0-9_-]*;```

I would like to add escaping support into Pinot.

This functionality could be accomplished by escaping or enclosing (back-ticks). ie-

Escaping Example:
```select my\.field from data```

Enclosing Example:
```select `my.field` from data```

Would this be a welcome contribution?  If so let me know if you have a preference in regard to escaping vs. enclosing (or possibly some other method).

Thank you

**Comment by kishoreg** [comment]
We can change the regex for identifier in Pql .g4 to allow . In the column name. Can you try it and let us know if it works? You can submit the PR with a test case.

**Comment by subprotocol** [comment]
Sure, I would be happy to.

For a quick and dirty test I tried:
```IDENTIFIER: [A-Za-z_][.A-Za-z0-9_-]*;```

It did break group by queries. Removing this from expression in the grammar fixed it:
```  | IDENTIFIER '.' IDENTIFIER                   # Identifier```


While this works, I think the downside to directly allowing '.' in IDENTIFIER is that it may break future queries that could involve tables references.  For example-

1. table.name.of.column
2. table.name\\.of\\.column
3. table.\`name.of.column\` or \`table\`.\`name.of.column\`

1 is ambiguous because you can't really know which part is the table and which part is the column.

I think 2 and 3 are both doable. If I had a preference I would go with 3 (mysql is able to escape identifiers in this manor: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html).

As I see it implementing 3 would require two small changes:

- Change IDENTIFIER to allow back-tick wrapped identifiers
- Currently IdentifierAstNode only has getName(), which returns the value.  For purposes of re-compilation (ie- GroupByAstNode calling groupBy.addToExpressions(groupByColumnName)), IdentifierAstNode would need an additional method that returns the identifier expression as it was passed in.

For example, the column \`name.of.column\`:
- IdentifierAstNode.getName would return **name.of.column**
- IdentifierAstNode.getExpression (which would be introduced) would return **\`name.of.column\`** and be passed into things like groupBy.addToExpressions


Before I put together a PR let me know if I'm still on the right track and if you have a preference.

**Comment by kishoreg** [comment]
Great points!. Can you elaborate on why it broke group by queries? Did it fail in parsing the query or executing it.

There are two parts to this. 
1. Changing the grammar so that we are future proof (have the ability to differentiate between table name and column name
2. Underlying pinot code is able to parse the table name and column

If I understand you correctly you are suggesting we do 1 and make minimal changes for us to handle it in group by expressions?. Note we plan we support expressions in selection and filter as well. Will your suggestion work for selection and group by as well. 

@jfim can you add your thoughts on this

**Comment by subprotocol** [comment]
Oops sorry, I misspoke.  I had some other code in there that was messing up group by.  Adding '.' to IDENTIFIER in fact does not break anything and seems to work great (future proofing issues aside).

> If I understand you correctly you are suggesting we do 1 and make minimal changes for us to handle it in group by expressions?

Yes, this is correct.

> Will your suggestion work for selection and group by as well.

Yes, also correct.  I just took the liberty of implementing backtick escaped identifiers.  Turns out it wasn't too much trouble to implement.  Please let me know if my approach is ok: https://github.com/subprotocol/pinot/commit/d66bca8088fc966bcae8ab44cbaf3478c39685ef

I am happy to make any adjustments that you or others see fit.  Just let me know if I'm on a good path. If so I will also put in unit tests and submit a PR.

**Comment by kishoreg** [comment]
can this be closed?

**Comment by subprotocol** [comment]
yes, thanks!
