### ISSUE TITLE
Error when close inverted index for column

### ISSUE THREAD

**Issue by left11** [linkedin/pinot#27]
This exception happens when SegmentTarPush
I hava three pageview log file, d1 d2 d3, after SegmentCreation, I push the index to controller,
d1 works fine with d3, but exceptions happens when pushing d2. It seems the index was broken(part of d1's data cannot be queried)

**Comment by left11** [comment]
the segments d1 generate seems to conflict with d2's

d1's segments 

/user/pinot/pv-segments/20150629/kuaizhan-pvs_16615_16615_1.tar.gz
/user/pinot/pv-segments/20150629/kuaizhan-pvs_16615_16615_2.tar.gz
/user/pinot/pv-segments/20150629/kuaizhan-pvs_16615_16615_3.tar.gz
.......


d2's segments 
/user/pinot/pv-segments/20150630/kuaizhan-pvs_16615_16615_0.tar.gz
 /user/pinot/pv-segments/20150630/kuaizhan-pvs_16615_16615_1.tar.gz
/user/pinot/pv-segments/20150630/kuaizhan-pvs_16615_16616_4.tar.gz
/user/pinot/pv-segments/20150630/kuaizhan-pvs_16616_16616_10.tar.gz
......

both has  /user/pinot/pv-segments/20150630/kuaizhan-pvs_16615_16615_1.tar.gz,  the 16615 is the field days_since_epoch?

**Comment by kishoreg** [comment]
yes. you can set the start time, end time explicitly while generating the
segments. It is a requirement for the segment names to be unique.
