### ISSUE TITLE
SIMPLE_DATE_FORMAT is not honoring output granularities

### ISSUE THREAD

**Issue by subprotocol** [linkedin/pinot#2729]
SIMPLE_DATE_FORMAT does not take into account output granularities.  This causes group by queries to incorrectly bucket timeseries data.

For example-

inputFmt: `1:MILLISECONDS:EPOCH`
outputFmt: `1:MILLISECONDS:SIMPLE_DATE_FORMAT:yyyy-MM-dd HH:mm:ss.SSS`
outputGranularity: `15:MINUTES`

given a time of `1523560598233L`  currently returns `2018-04-12 19:16:38.233` instead of the expected output: `2018-04-12 19:15:00.000`.

The fix appears to be very simple.  BaseDateTimeTransformer.transformMillisToSDF just needs call transformToOutputGranularity before being passed to the outputDateTimeFormatter.

Unless anyone has an objection I would be happy to put together a PR to fix this.

**Comment by Jackie-Jiang** [comment]
No bucketing in case of simple date format was intentional. Also, there are notes in BaseDataTimeTransformer.java line 30: "NOTE: time size, time unit and output granularity does not apply to simple date format."
Please refer to the comments in #2659

**Comment by subprotocol** [comment]
@Jackie-Jiang thank you for pointing me to that. The specific use-case I am after is allowing customers to query their data at different granularities and timezones as determined at query time.  For example Druid has support for querying in this mannor: http://druid.io/docs/latest/querying/granularities.html

@kishoreg sure thing thanks.

**Comment by Jackie-Jiang** [comment]
@kishoreg My initial PR has bucketing for SDF, but @npawar pointed out that we should not bucket for SDF, so I don't know if this would affect the current use case. @npawar Can you please verify that?

**Comment by subprotocol** [comment]
@Jackie-Jiang @kishoreg Here is my take on this- https://github.com/linkedin/pinot/pull/2738

**Comment by npawar** [comment]
Bucketing was left out, as it doesn't work correctly when timezone comes into the picture. 
inputFmt: 1:MILLISECONDS:EPOCH
outputFmt: 1:MILLISECONDS:SIMPLE_DATE_FORMAT:yyyy-MM-dd HH:mm:ss.SSS tz(America/Los_Angeles)
outputGranularity: 1:DAYS

In this case, convert inputFmt to millis and then millis to outputFmt works
But convert inputFmt to millis, bucket to days, convert millis to outputFmt will not work for some hours of the day
UTC millis April 18th 2018 10am  should convert to 2018-04-18 00:00:00
UTC millis April 18th 1 am should convert to 2018-04-17 00:00:00

If we bucket it first, both will return 2018-04-17, which is not desirable.

If you plan to bucket it even in SDF case, you will need to handle bucketing with time zone knowledge

**Comment by kishoreg** [comment]
Great point about handling timezone for sdf conversion. So looks like if the output format is sdf, we should first convert inputFmt to a DateTime (not millis) and call the right API on the DateTime to truncate.

https://stackoverflow.com/questions/4133682/jodatime-equivalent-of-dateutils-truncate

**Comment by Jackie-Jiang** [comment]
@kishoreg @npawar If input and output have different time zone, which one should we pick to apply the bucketing? IMO, maybe always apply bucketing on epoch time is acceptable, we just need to document that.

**Comment by npawar** [comment]
@Jackie-Jiang bucketing on epoch time would be wrong. It will fail for the example I provided. Input in millisSinceEpoch but output in sdf with timezone changed was exactly the usecase why we added timezone support. In such cases it would be right to apply bucketing with timezone knowledge, or, do the bucketing after applying the output format conversion perhaps (inputFormat -> millis -> outputFormat -> bucket)

**Comment by Jackie-Jiang** [comment]
@npawar So you mean bucketing should always based on the output time zone right? I thinks that make sense to me.

**Comment by kishoreg** [comment]
+1 on @npawar comment. Do the bucket after converting it to the outputformat. @subprotocol, what do you think

**Comment by kishoreg** [comment]
yes, that's sounds right.
