### ISSUE TITLE
Proposal: implementing kafka high level consumer lag reports in pinot controller

### ISSUE THREAD

**Issue by jamesyfshao** [linkedin/pinot#3004]
Currently, There is no good way to monitor if pinot realtime server consumer is catching up with the input kafka topic latest data. We currently use the ingestion rates reported by pinot realtime server. However, it is fairly easy for this monitoring to generate false positive or false negative. A better way to monitor such behavior is to monitor the lag between pinot realtime server last committed offset and the latest offset of that kafka topic. 

To allow Pinot users to set up this lag monitor easily, we can add a new lag monitoring & reporting thread in Pinot Controller. We will use the kafka topic name, zookeeper, groupid and assigned partition id to fetch the latest offset of that kafka partition and offset of high-level kafka consumer. We will then emit the lag to Metrics module of pinot controller. We should also make this monitoring component pluggable so users using different versions of Kafka can use the appropriate library to implement their own offset report logic.

Other alternatives:
1. pinot-server report lag within server instance:
Overall we think it is dangerous to let a service component to do self health check. If there are some issues with pinot-server that cause consumption to stop, there is a high chance that the same issues impact the self health check components on pinot-server.

2. monitoring with external kafka offset checking services (Burrow):
Because pinot uses a unique consumer group id everytime we add a new table, it is tricky to let external service to discover pinot consumer group id correctly. We could also delete table/server which will cause old consumer group offset to increase and introduce false positive.

Let us know what do you think about this proposal. We are planning to work on this feature in next months to fill in the gap of our pinot monitoring.

**Comment by kishoreg** [comment]
how can we extend this to low level consumer as well.

**Comment by mcvsubbu** [comment]
@kishoreg pinot low level consumer already has a reported metric for the lag. SimpleConsumer provides the highest offset availble, and the difference between the highest consumed offset and the highest offset is reported as the consumer lag on a per topic-partiton basis.

**Comment by mcvsubbu** [comment]
@jamesyfshao the 'offset' you talk about is a vector in the HighLevel stream consumer -- offset in each partition. In theory, it is possible that a Pinot HL consumer is starved trying to consume data from a particular consumer. It is certainly possible that some partitions lag a lot more than others, so I am not sure what a 'lag' metric here will be.  Let us assume it is a function of lag of N partitions.

You will need to monitor this on a per pinot consumer basis. You want to know how much a particular consumer is lagging, I suppose

So, there should be no need of a separate thread in HLC. If you can get the current available offset (and the committed offset) just after the commit in the High level kafka consumer, you should be able to update the metric.

**Comment by mcvsubbu** [comment]
Correct, and that was my proposal to @jamesyfshao  as well (to evaluate and emit the metric at the time we commit, on the server rather than controller).

I am just not sure what the evaluated metric would be, though.

Since we are moving in the direction of a generic stream, I would want this evaluation to be done inside the specific consumer code.

@jamesyfshao  can you elaborate further on how you are planning to compute the metric?

Another idea (like you mentioned) is to monitor using external Kafka monitoring services. That worked well for us, and you may want to look into  it.

Also, you should strongly consider moving to LLC.

**Comment by jamesyfshao** [comment]
@mcvsubbu @kishoreg  the lag I referred above is the difference between the latest offset(high-water mark) of a particular kafka input topic partition and the consumer last committed offset for that topic. There are multiple scenarios that lag might increase:

1. kafka input topic has surge in traffic and pinot consumer is not able to catch up, causing the lag to increase
2. misconfig/bugs in a particular pinot server caused it to slow down or stuck and not able to catch up with kafka input topic
3. bug in kafka consumers that cause reset offset to an earlier offset.

If we have a pinot component that can help us to calculate the lag between the latest available offset for each partition and our consumer last committed offset and emit this information to pinot Metrics, pinot users would be able to set up alerts based on this "lag" number, either based on per-partition lag value or aggregated lag value. The scenarios we mentioned above would be captured easily.

I would say putting such calculation in kafka consumer within pinot server would also be a great way to do it. The only problem is that it will not be able to catch scenario No.2 I listed above. However, it is a really uncommon issue and we could ignore it for now.

For using external Kafka monitoring service, it would be great if it is already available within users' infrastructure but it is an external dependency that we will require pinot users to set up and operate. I feel like it would be better if we could provide users means to achieve the same goal without setting up such external dependency. Also adding/removing consumer group to monitor (for HLC at least) when we add/remove pinot table is tricky to automated with external monitor services (with the reason I mentioned above).

If it sounds good, we will spend more time investigating implementing such metrics calculation logics within kafka consumer

**Comment by kishoreg** [comment]
Agree with you that depending on external kafka monitoring service is not ideal.

@jamesyfshao can we compute the offset in the controller without contacting individual servers?

Irrespective of the solution we pick, we definitely need to generalize this to support various kafka versions (including hlc and llc), and other streaming sources.

**Comment by jamesyfshao** [comment]
> @jamesyfshao can we compute the offset in the controller without contacting individual servers?

It is possible to compute offset in controller (at least for hlc consumer) as pinot store the information about consumer group id, partition under property store zk node.

Example zknode content about this info:

```
$ zkcli get <parent zk node>/PROPERTYSTORE/CONFIGS/INSTANCE/<server_node>

('{\n  "id":"<server node>"\n  ,"simpleFields":{\n  }\n  ,"listFields":{\n  }\n  ,"mapFields":{\n    "KAFKA_HLC_GROUP_MAP":{\n      "<realtime table name>":"<consumer group id>"\n      ....    }\n    ,"KAFKA_HLC_PARTITION_MAP":{\n      "<realtime table name>":"<partition id>"\n          }\n  }\n}', ZnodeStat(...))
```

table config about zookeeper and topic name can be retrieved in zookeeper node  `<parent node>/PROPERTYSTORE/CONFIGS/TABLE/<table name>`.

Pinot controller should have access to those info. for example, class `PinotRealtimeSegmentManager` has access to groupid/partition-id through **`_pinotHelixResourceManager.getInstanceZKMetadata(instanceId)`** and table info through `HelixInstanceDataManager`. But I have to admit it is a fairly early investigation and we have not looked into llc cases and other streaming solutions. We will definitely do more investigation once we have more ideas about which direction we want to focus on

**Comment by mcvsubbu** [comment]
Pinot controller only has info on the group ID.

It does not have info on offset up to which each partition has consumed. Neither does it have info on what the offset is in Kafka. Since we use Kafka's commit code, this info is stored by Kafka in whatever format they seem fit in some location unknown to Pinot. I would not want Pinot to be dependent on this format or location (which may change across Kafka versions, we don't know).

It seems to me that any which way you try to get these two pieces of information, it will be a re-write of the tools that Kafka may provide, to compute offset lag. Have you looked at any Kafka tools, and tried to use them?

Like I mentioned before, LLC already has the problem solved, so have you considered moving to LLC?

**Comment by jamesyfshao** [comment]
will reinvestigate llc and see if how we can utilize it to help us to get this information, thanks for all suggestions!
