### ISSUE TITLE
wiki article improvement on low level consumer benefits

### ISSUE THREAD

**Issue by jamesyfshao** [linkedin/pinot#3107]
Hi @mcvsubbu 

Could we add a simple comparison (pros & cons) between the low-level kafka consumer and high-level kafka consumer in the low-level kafka consumer wiki? we are currently experimenting with low-level kafka consumer and it would be great if there is a summary on the benefits of the migration. We would also add some sections on how to migrate from high-level consumer to low-level consumer later as we do the migration.

**Comment by mcvsubbu** [comment]
OK, let me see how we can get this done.

**Comment by jamesyfshao** [comment]
sounds great! looking forward to it

**Comment by mcvsubbu** [comment]
I have added some more to the Low Level Kafka design document. Hopefully this helps.

**Comment by jamesyfshao** [comment]
looks great! will definitely take a look!
