### ISSUE TITLE
Add support for spaces/other characters in Pinot Segment Names

### ISSUE THREAD

**Issue by jenniferdai** [linkedin/pinot#3159]

**Comment by jenniferdai** [comment]
https://github.com/linkedin/pinot/pull/3153

**Comment by kishoreg** [comment]
Did we already implement this. why do we want to support this?

**Comment by jenniferdai** [comment]
We did. I momentarily removed it in the big refactor and was asked to create this but added it back in the same one after some discussion.

**Comment by kishoreg** [comment]
Who is asking for this feature

**Comment by jenniferdai** [comment]
Internal customers needed it
