### ISSUE TITLE
How to check if all segments are loaded during server restart

### ISSUE THREAD

**Issue by fx19880617** [linkedin/pinot#3247]
We recently hit an issue that, during rolling restart, we have some servers taking about 10 mins(Many tables/segments are co-located) to load all the segments. However the health check will treat server is up once http endpoint is up. This caused some tables are actually serving partial data during restart.

Is it possible to expose some apis about server status(bootstrap/online/shutting_down/offline)?

**Comment by kishoreg** [comment]
We check for EV = IS after restart. Pinot server sets
shutdownInProgress=true when the node is shutting down. During restart, we
set shutdownInProgress=false as soon as we start instead of waiting for EV
= IS. We need to flip that order. Can you make that change if
possible. Note the drawback of this is we might never have EV =IS in some
cases and we will not serve any segments. We should have a timeout after
which we mark the server ready.

**Comment by fx19880617** [comment]
Sounds good, I could change for that order. Also we need to expose a health check endpoint through api resources.

**Comment by Jackie-Jiang** [comment]
In ServiceStatus.java. there is a static method getServiceStatus() to return the server status (STARTING/GOOD/BAD). We can easily add an api resource to hook this up.

**Comment by sunithabeeram** [comment]
In addition to updating server startup, we can ensure that the server doesn't shutdown until the segments its serving get offlined in EV. ie, after https://github.com/linkedin/pinot/blob/master/pinot-server/src/main/java/com/linkedin/pinot/server/starter/helix/HelixServerStarter.java#L219, we could wait till the segments are offline; that way, when the server comes back up, EV does not have any pointers to it and broker won't route to it.

With this, we can keep the server startup timeout short.

**Comment by fx19880617** [comment]
Not with helix upgrade. We are still using helix 0.6.8.
I think this issue is there for a while. We recently added more data quality monitoring, hence we discovered this issue during rolling restart.

**Comment by sunithabeeram** [comment]
Thats good to know. Thanks for the info @fx19880617.

**Comment by fx19880617** [comment]
> rver startup, we can ensure that the server doesn't shutdown until the segments its serving get offlined in EV. ie, after https://github.com/linkedin/pinot/blob/master/pinot-server/src/main/java/com/linkedin/pinot/server/starter/helix/HelixServerStarter.java#L219, we could wait till the segments are offline; that way, when the server comes back up, EV does not have any pointers to it and broker won't route to it.

I think server will mark itself as shutdownInProgress, which broker will ignore it from building routing table. So we should be fine.

**Comment by fx19880617** [comment]
Fixed in https://github.com/linkedin/pinot/pull/3253
