### ISSUE TITLE
StartServerCommand.class ,line 139 ,has a bug

### ISSUE THREAD

**Issue by dongyanfeng** [linkedin/pinot#36]
Configuration configuration = readConfigFromFile(_configFileName);
    if (configuration == null) {
      if (_configFileName != null) {
        LOGGER.error("Error: Unable to find file {}.", _configFileName);
        return false;
      }
      configuration = new PropertiesConfiguration();   //useless

**Comment by mayankshriv** [comment]
@dongyanfeng Can you elaborate why line 139 is useless? Code execution will reach line 139 iff configuration == null. And if it is null, you would need to create a new object. Please let me know if I am missing something.
