### ISSUE TITLE
EXTRA_JVM_ARGUMENTS in pinot-admin.sh prevents configuration of log4j file and -Xms -Xmx

### ISSUE THREAD

**Issue by jpbetz** [linkedin/pinot#47]
Currently the only way to increase log verbosity from ERROR to INFO on pinot is to modify the pinot-log4j.properties file inside the pinot distribution.

The main problem is that `pinot-admin.sh` appends the `EXTRA_JVM_ARGUMENTS` JVM properties *after* the user provided `JAVA_OPTS`.

This causes a few problems.

* There is no simple way to specify an alternate log4j file.  Usually this is would simply be done by adding `-Dlog4j.configuration=...` to JAVA_OPTS, but `EXTRA_JVM_ARGUMENTS` overrides the settings.
* Any `-Xms` or `-Xmx` settings provided in JAVA_OPTS are ignored.

Given that pinot has complex classpath, developer really must start it using `pinot-admin.sh`.  And in order to properly operate and debug pinot, developers will often need to increase log verbosity and properly tune JVM settings.

**Comment by mayankshriv** [comment]
The issue has been resolved. You can set the env variable JAVA_OPTS to overwrite the defaults being used by pinot-admin. Please let us know if you have issues with the same.
