### ISSUE TITLE
quick-start-realtime.sh gives exception on the start "URI is not hierarchical"

### ISSUE THREAD

**Issue by amorskoy** [linkedin/pinot#5]
I've build pinot according to README

/var/www/RnD/pinot/pinot-distribution/target/pinot-0.016-pkg/bin$ ./quick-start-realtime.sh
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at com.linkedin.pinot.tools.RealtimeQuickStart.main(RealtimeQuickStart.java:35)

/var/www/RnD/pinot/pinot-distribution/target/pinot-0.016-pkg/bin$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by amorskoy** [comment]
Sorry, resolved. See
https://github.com/linkedin/pinot/issues/4

**Comment by swordflychen** [comment]
Why not to write out the solution?
