### ISSUE TITLE
Having clause support

### ISSUE THREAD

**Issue by flowbehappy** [linkedin/pinot#53]
Hi! Any chance to get having clause supported? As it is so important in OLAP.

**Comment by jfim** [comment]
@flowbehappy, we'll eventually have it, but I don't have an estimate as to when.

**Comment by dhaval2025** [comment]
we will update the docs once we have 'having' support

**Comment by taotaojs** [comment]
Hi, Does Pinot support the Having? We need the feature!

**Comment by kishoreg** [comment]
Having is not yet supported. Hopefully we can get to this asap
