### ISSUE TITLE
Incorrect secondary ordering

### ISSUE THREAD

**Issue by gregspurrier** [linkedin/pinot#61]
Using quick-start-offline.sh with the repository as of commit dd3b058bc10d04f61374fd050b467440b756e7f2, a secondary ordering term is not working as expected.

For example, `curl -X POST -d '{"pql":"select yearID, playerName from baseballStats order by yearID, playerName"}' http://localhost:7000/query` yields:

```json
{
  "selectionResults": {
    "columns": [
      "yearID",
      "playerName"
    ],
    "results": [
      [
        "1871",
        "Caleb Clark"
      ],
      [
        "1871",
        "Asahel"
      ],
      [
        "1871",
        "Arthur Algernon"
      ],
      [
        "1871",
        "Andrew Jackson"
      ],
      [
        "1871",
        "Alfred L."
      ],
      [
        "1871",
        "Alfred James"
      ],
      [
        "1871",
        "Albert Goodwill"
      ],
      [
        "1871",
        "Albert G."
      ],
      [
        "1871",
        "Adrian Constantine"
      ],
      [
        "1871",
        "Calvin Alexander"
      ]
    ]
  },
  "traceInfo": {},
  "numDocsScanned": 97889,
  "aggregationResults": [],
  "timeUsedMs": 20,
  "segmentStatistics": [],
  "exceptions": [],
  "totalDocs": 97889
}
```

Notice that the playerName values in the grouping are not in the correct order.

**Comment by kishoreg** [comment]
Found the issue, we fail to compare the second column if the first column is same. https://github.com/linkedin/pinot/blob/bcf6dc5f34dfd13c1a2e2b1ae5750b4b07b9f254/pinot-core/src/main/java/com/linkedin/pinot/core/query/selection/SelectionOperatorService.java#L285

Fix is to not return if the compareTo returns 0 within the for loop

**Comment by jfim** [comment]
Fixed by https://github.com/linkedin/pinot/commit/56826f131d83fd8aa7086f6ccd8e2d301093fcba

**Comment by gregspurrier** [comment]
@kishoreg thanks for the rapid fix!
