### ISSUE TITLE
Inverted Index

### ISSUE THREAD

**Issue by alvinhom** [linkedin/pinot#7]
Can you explain how the inverted index is used within Pinot?  I have used Druid previously, and they implement a bitmap index for the dimensions so they can do very fast filtering on low cardinality data sets.  I imagine the inverted index is used similarly here, but it is not documented.  

Also, may I suggest having a Google group so these questions can go there instead.

**Comment by dhaval2025** [comment]
hey @alvinhom , pinot does create and use inverted index for dimensional filtering, we use roaring bitmap for inverted index compression. Using and creating Inverted index is configurable on a per column basis, sometimes simply sorting the date on a column which is always filtered upon is good enough to achieve fast query response times, in which case we can avoid using inverted index to filter on other columns, this helps us to server more data off of ram. 

Hope that helps, Also the google groups should be up soon. 

Regards
Dhaval

**Comment by kishoreg** [comment]
Adding to what Dhaval said, there is also ability to configuring a column
as the leading key. For example, if you have userData, userId can be the
leading key. We create a different type of index (sorted index) for the
leading keys and we have seen that this improves the performance
significantly.

Thanks for pointing out the missing documentation. We will add it.

thanks,
Kishore G

**Comment by dhaval2025** [comment]
google groups created... 

https://groups.google.com/forum/#!forum/pinot_users

will be updating the documentation as well to point to this

**Comment by lemire** [comment]
Format specification for Roaring bitmaps : https://github.com/RoaringBitmap/RoaringFormatSpec/
