### ISSUE TITLE
Switch to GitHub PR-based development

### ISSUE THREAD

**Issue by brandtg** [linkedin/pinot#71]
It would be great to switch to GitHub PR-based development and review as opposed to pushing from internal LinkedIn branches.

This will help expand the community around Pinot and make it a first-class piece of open source software.

Currently Druid does a much better job of engaging the community, and Pinot will not be able to compete under its current model.

This will also allow key Pinot engineers (@dhaval2025, @fx19880617) to maintain a higher level of engagement if they can.

**Comment by kishoreg** [comment]
Hi Greg,

This is good idea and something that has been pending from our side. We
will get this done over the holidays.

thanks,
Kishore G

**Comment by brandtg** [comment]
Awesome, thanks @kishoreg !

**Comment by otisg** [comment]
+10 for this.  This project will not succeed unless it properly opens up (c.f. Voldemort)

**Comment by jfim** [comment]
All development on Pinot now goes through GitHub pull requests. :)
