### ISSUE TITLE
LLC consumer initial setup can point to an invalid offset

### ISSUE THREAD

**Issue by jfim** [linkedin/pinot#725]
**LLC is NOT enabled by default and is still experimental, this is a discussion about a feature which is not currently enabled.**

When creating a new LLC realtime table, the controller determines the initial offset for consumption. If this is set to smallest and the Kafka retention process reaps that offset, consumers will get invalid offset exceptions. This can happen if servers are not already started when creating a new LLC realtime table or if servers are down for an extended period of time that is longer than the Kafka retention period. Unfortunately, this is a silent failure that can only be diagnosed by exceptions happening in the logs (and a 0 consumption rate metric).

The current workaround for this is to drop and recreate the realtime table, but this is cumbersome.

**Comment by mcvsubbu** [comment]
Fixed as of https://github.com/linkedin/pinot/pull/898

The validation manager will auto-create segments
