### ISSUE TITLE
About the pinot data persistence

### ISSUE THREAD

**Issue by daifish** [linkedin/pinot#78]
Excuse me, I am a newer to use the pinot, Now i use pinot to build a Log System
When i readed the how-to-use-pinot, i found that the pinot created a table we used, but when the server is shutdown, the data from the created table would loss.
So, i want to know the pinot whether have the data persistence policy or not? If the answer is yes, can tell me where i should read? If not, can give me some Suggestions to solve the problem?
Thank you very much

**Comment by xuyang2** [comment]
+1

**Comment by daifish** [comment]
@xuyang2 Hi, i have solve this problem, u should assign the --dataDir when u start the broker, server, controller, by default they all use /tmp, when the machine restart, the /tmp will loss, hope that can help u
